server:
  port: 8080
  url: http://localhost:8080
# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode: false
logging:
  level:
    org.atmosphere: WARN
database:
  url: http://localhost:9090/rdf4j-server
  repository: znalosti.gov.sk2

---
# This configuration is for cases when you proxy DB server from znalosti.gov.sk
spring:
  config:
    activate:
      on-profile: docker-test
server:
  port: 7070  
  url: http://localhost:7070
local:
  server:
    port:7070
database:
  url: http://localhost:8080/rdf4j-server 
---
spring:
  config:
    activate:
      on-profile: prod

database:
  url: http://rdf-server:8080/rdf4j-server
      
