server:
  port: 8080
  url: http://localhost:8080
# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode: false
  excludeUrls: /integration/api/docs/swagger-ui/**
 
logging:
  level:
    org.atmosphere: WARN
database:
  url: http://localhost:9090/rdf4j-server
  repository:
    znalosti: znalosti.gov.sk
    refid: refid
  reset-db-allowed: false
  source-data:
    github-url: https://api.github.com/repos/slovak-egov/centralny-model-udajov
users:
  integration:
    metais:
      username: admin
      password: admin

# swagger-ui custom path
springdoc:
  pathsToMatch: /integration/api/**
  swagger-ui:
    enabled: true
    path: /integration/api/docs/swagger-ui/index.html
  api-docs:
    enabled: true
    path: /integration/api/docs/api-docs
---
# This configuration is for cases when you proxy DB server from znalosti.gov.sk
spring:
  config:
    activate:
      on-profile: test-with-proxy
logging:
  level:
    org.atmosphere: WARN
    sk.gov.knowledgegraph: DEBUG
server:
  port: 7070  
  url: http://localhost:7070
local:
  server:
    port:7070
database:
  url: http://localhost:8080/rdf4j-server
  repository: 
    znalosti: znalosti.gov.sk
    refid: refid-test
  reset-db-allowed: true
  
---
# This configuration is for test environment on znalosti.gov.sk server
spring:
  config:
    activate:
      on-profile: test
database:
  url: http://rdf-server:8080/rdf4j-server
  repository:
    znalosti: znalosti.gov.sk-test
    refid: refid-test
  reset-db-allowed: false
  
---
spring:
  config:
    activate:
      on-profile: prod

database:
  url: http://rdf-server:8080/rdf4j-server
  repository: 
    znalosti: znalosti.gov.sk
    refid: refid
  reset-db-allowed: false
    