PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix dcat: <http://www.w3.org/ns/dcat#> prefix dct: <http://purl.org/dc/terms/>
prefix skos: <http://www.w3.org/2004/02/skos/core#> select distinct ?score ?type ?prefLabel ?title ?label ?typeLabel where
{  <https://data.gov.sk/def/ontology/legal-subject/LegalSubject> rdf:type ?type .   
      graph ?q {
       ?type rdfs:label ?typeLabel .
       filter langMatches( lang(?typeLabel), "sk" ) }
  graph ?g { {
     <https://data.gov.sk/def/ontology/legal-subject/LegalSubject> skos:prefLabel ?prefLabel .
     bind (1 as ?score)
     filter langMatches( lang(?prefLabel), "sk" ) 
    } union {
     <https://data.gov.sk/def/ontology/legal-subject/LegalSubject> dct:title ?title .
     bind (2 as ?score)     
     filter langMatches( lang(?title), "sk" ) 
    } union {
     <https://data.gov.sk/def/ontology/legal-subject/LegalSubject> rdfs:label ?label .
     bind (3 as ?score)           
     filter langMatches( lang(?label), "sk" ) 
    } } } order by desc(?score) limit 1