prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix dct: <http://purl.org/dc/terms/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

select distinct ?publisher ?publisherName ?dataset ?datasetTitle ?catalog ?catalogTitle ?theme where
{ graph ?g {
    ?catalog rdf:type dcat:Catalog .
    ?catalog dct:title ?catalogTitle .
    ?catalog dcat:dataset ?dataset .
    ?dataset rdf:type dcat:Dataset .
    ?dataset dct:title ?datasetTitle .
    ?dataset dct:publisher ?publisher .
    ?dataset dcat:theme ?theme .
    FILTER langMatches( lang(?catalogTitle), "sk" )
    FILTER langMatches( lang(?datasetTitle), "sk" )
  } graph ?g2   {
     ?publisher skos:prefLabel ?publisherName .
     FILTER langMatches( lang(?publisherName), "sk" ) }
} order by asc(?publisherName) asc(?datasetTitle) asc(?catalogTitle)