prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> prefix dcat: <http://www.w3.org/ns/dcat#>
prefix dct: <http://purl.org/dc/terms/> prefix skos: <http://www.w3.org/2004/02/skos/core#>
select distinct ?currentCatalog ?catalogTitle ?currentDataset ?datasetTitle ?publisher ?publisherName ?theme ?themeLabel ?version where {
?catalog rdf:type dcat:Catalog .
?catalog dct:title ?catalogTitle .
FILTER langMatches( lang(?catalogTitle), "sk" )
?catalog dcat:hasCurrentVersion ?currentCatalog .
?currentCatalog dcat:dataset ?currentDataset .
?dataset dcat:hasCurrentVersion ?currentDataset .
?dataset dct:title ?datasetTitle .
  FILTER langMatches( lang(?datasetTitle), "sk")
?currentDataset dcat:version ?version .
?currentDataset dct:publisher ?publisher .
?publisher skos:prefLabel ?publisherName .
FILTER langMatches( lang(?publisherName), "sk" )
?dataset dcat:theme ?theme .
?theme skos:prefLabel ?themeLabel .
FILTER langMatches( lang(?themeLabel), "sk" )
} order by asc(?catalogTitle)  asc(?datasetTitle)