prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> prefix dcat: <http://www.w3.org/ns/dcat#>
prefix dct: <http://purl.org/dc/terms/> prefix skos: <http://www.w3.org/2004/02/skos/core#>
select distinct ?subject ?object ?graph ?graphName where
{  
  graph ?graph {
    ?subject ?predicate ?object .
    filter not exists {?subject dcat:hasCurrentVersion ?currentDataset}
    filter regex(?object,"dataset", "i")
    filter (lang(?object)= "sk")}
    ?graph dct:title ?graphName
    filter (lang(?graphName)= "sk")}